//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSchedule
    {
        public int ScheduleId { get; set; }
        public int ClassId { get; set; }
        public byte DayOfWeek { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Room { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
